version: '4'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - bitway
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - bitway
    env_file:
      - .env.development
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bitway
    
networks:
  bitway:
    driver: bridge
