# Set runner
FROM node:18-alpine3.16 as runner

WORKDIR /app/backend

# Install pnpm globally
RUN npm install -g pnpm

# Copy package.json and pnpm-lock.yaml (if available)
COPY ./backend /app/backend/

# Install project dependencies
RUN pnpm install
RUN npx prisma generate


# Expose port and start app
EXPOSE 8000
EXPOSE 80
ENTRYPOINT ["pnpm", "run", "dev"]
