# Set runner/*
FROM node:18-alpine3.16 as runner

WORKDIR /app/backend

# Install pnpm globally
RUN npm install -g pnpm

COPY ./backend /app/backend/

ARG POSTGRES_HOST
ARG POSTGRES_PWD
ENV DATABASE_URL="postgresql://postgres:${POSTGRES_PWD}@${POSTGRES_HOST}:5432/postgres?schema=public"

# Install project dependencies
RUN pnpm install
RUN npx prisma generate

# Expose port and start app
EXPOSE 8000
EXPOSE 80
ENTRYPOINT ["pnpm", "run", "start:prod:migrate"]
